# This is a basic workflow that is manually triggered

name: auto

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches: ['master']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  createPullRequest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: create pr
      uses: peter-evans/create-pull-request@v3
      with:
        base: master-oem
        token: ${{ steps.generate-token.outputs.token }}
        title: '[Example] Update report'
        branch: ${{ github.head_ref }}
        body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]: 
